project:
  type: website
  output-dir: docs

website:
  title: "ES335: Machine Learning"
  description: "Machine Learning course at IIT Gandhinagar, August 2025"
  favicon: images/logo.jpeg
  navbar:
    background: "#ffffff"
    foreground: "#333333"
    logo: images/logo.jpeg
    logo-alt: "ES335 Logo"
    title: false
    right:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: grading.qmd
        text: Grading
      - href: faq.qmd
        text: FAQ
      - href: tentative.qmd
        text: Deadlines
      - href: https://nipunbatra.github.io
        text: Instructor
  page-footer:
    left: "ES335: Machine Learning • IIT Gandhinagar • August 2025"
    right: "Made with [Quarto](https://quarto.org) • [Prof. Nipun Batra](https://nipunbatra.github.io)"
    background: "#f8fafc"

format:
  html:
    theme: [cosmo, styles.scss]
    css: [styles.scss]
    toc: false
    page-layout: full
    smooth-scroll: true
    highlight-style: github
    mainfont: "Inter, system-ui, -apple-system, sans-serif"
    monofont: "JetBrains Mono, Monaco, Consolas, monospace"
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true
    anchor-sections: true
    fig-responsive: true
    
execute:
  freeze: auto

