project:
  type: website
  output-dir: docs

website:
  title: "ES335: Machine Learning"
  description: "Machine Learning course at IIT Gandhinagar, August 2025"
  favicon: images/logo.jpeg
  navbar:
    background: "#ffffff"
    foreground: "#333333"
    logo: images/logo.jpeg
    logo-alt: "ES335 Logo"
    title: "ES335"
    right:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: grading.qmd
        text: Grading
      - href: faq.qmd
        text: FAQ
      - href: tentative.qmd
        text: Deadlines
      - href: https://nipunbatra.github.io
        text: Instructor

format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [cosmo, styles-dark.scss]
    css: [styles.scss]
    toc: true
    toc-location: right
    toc-depth: 3
    smooth-scroll: true
    highlight-style: github
    mainfont: "Inter, system-ui, -apple-system, sans-serif"
    monofont: "JetBrains Mono, Monaco, Consolas, monospace"
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true
    anchor-sections: true
    fig-responsive: true
    
execute:
  freeze: auto

